# Generated by {sdf}

# Required generics -------------------------------------------------------
# These are the minimal required s3 generics to get basic functionality of
# `sdf`.

# Must return TRUE for your class
#' @export
is_geometry.{{class_name}} <- function(x) {
  inherits(x, "{{class_name}}")
}


# If your class implements a wk handler, the default method will work.
#' @export
bounding_box.{{class_name}} <- function(x) {
  # TODO
}

# This must return a single geometry from a vector of geometries
#' @export
combine_geometry.{{class_name}} <- function(x) {
  # TODO
}

# Predicates --------------------------------------------------------------
# Predicates are optional, but enable the use of `sdf_join()`. Predicates
# should return a sparse matrix list representation. The elements the list
# are an integer vector indicating the features where the predicate is `TRUE`.
# The vector must be the _row position_.

#' @export
sdf_intersects.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_contains.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_within.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_crosses.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_covers.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_covered_by.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_equals.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_disjoint.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_touches.{{class_name}} <- function(x, y, ...) {
  # TODO
}


#' @export
sdf_overlaps.{{class_name}} <- function(x, y, ...) {
  # TODO
}


# Optional -----------------------------------------------------------------
# These are optional functions for the sdf interface.

#' @export
union_geometry.{{class_name}} <- function(x) {
  # TODO
}

#' @export
simplify_geometry.{{class_name}} <- function(x, ...) {
  # TODO
}

#' @export
buffer_geometry.{{class_name}} <- function(x, distance, ...) {
  # TODO
}

#' @export
centroid.{{class_name}} <- function(x) {
  # TODO
}

#' @export
convex_hull.{{class_name}} <- function(x) {
  # TODO
}

#' @export
concave_hull.{{class_name}} <- function(x, concavity, ...) {
  # TODO
}

