# Generated by {sdf}

# Required generics -------------------------------------------------------
# These are the minimal required s3 generics to get basic functionality of
# `sdf`.

# Must return TRUE for your class
#' @export
is_geometry.s2_geometry <- function(x) {
  inherits(x, "s2_geometry")
}


# If you class implements a wk handler, the default method will work.
#' @export
bounding_box.s2_geometry <- function(x) {
  bbox <- s2::s2_bounds_rect(s2::s2_union_agg(x))
  names(bbox) <- c("xmin", "ymin", "xmax", "ymax")
  bbox
}

# This must return a single geometry from a vector of geometries
#' @export
combine_geometry.s2_geometry <- function(x) {
  s2::s2_rebuild_agg(x)
}

# Predicates --------------------------------------------------------------
# Predicates are optional, but enable the use of `sdf_join()`. Predicates
# should return a sparse matrix list representation. The elements the list
# are an integer vector indicating the features where the predicate is `TRUE`.
# The vector must be the _row position_.

#' @export
sdf_intersects.s2_geometry <- function(x, y, ...) {
  s2::s2_intersects_matrix(x, y, ...)
}


#' @export
sdf_contains.s2_geometry <- function(x, y, ...) {
  s2::s2_contains_matrix(x, y, ...)
}


#' @export
sdf_within.s2_geometry <- function(x, y, ...) {
  s2::s2_within_matrix(x, y, ...)
}


#' @export
sdf_covers.s2_geometry <- function(x, y, ...) {
  s2::s2_covers_matrix(x, y, ...)
}


#' @export
sdf_covered_by.s2_geometry <- function(x, y, ...) {
  s2::s2_covered_by_matrix(x, y, ...)
}


#' @export
sdf_equals.s2_geometry <- function(x, y, ...) {
  s2::s2_equals_matrix(x, y, ...)
}


#' @export
sdf_disjoint.s2_geometry <- function(x, y, ...) {
  s2::s2_disjoint_matrix(x, y, ...)
}


#' @export
sdf_touches.s2_geometry <- function(x, y, ...) {
  s2::s2_touches_matrix(x, y, ...)
}


# Optional -----------------------------------------------------------------
# These are optional functions for the sdf interface.

#' @export
union_geometry.s2_geometry <- function(x) {
  s2::s2_union_agg(x)
}

#' @export
simplify_geometry.s2_geometry <- function(x, tolerance,...) {
  s2::s2_simplify(x, tolerance, ...)
}

#' @export
buffer_geometry.s2_geometry <- function(x, distance, ...) {
  s2::s2_buffer_cells(x, distance, ...)
}

#' @export
centroid.s2_geometry <- function(x) {
  s2::s2_centroid(x)
}

#' @export
convex_hull.s2_geometry <- function(x) {
  s2::s2_convex_hull(x)
}
